[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader_api = "0.11.15"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.8"
uart_16550 = "0.3.2"
volatile = "0.2.7"
x86_64 = "0.15.4"
pic8259 = "0.10.4"
pc-keyboard = "0.8.0"
libm = "0.2.11"
